In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns

In [ ]:
df= pd.read_csv("RIT+Opportunity+Wise+Data+-+Sheet1.csv")

df_before = df.copy()

In [ ]:
#Total Records
df.shape

(8558, 16)

In [ ]:
df.head()

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date
0,06/14/2023 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Faria,01/12/2001,Female,Pakistan,Nwihs,Radiology,03/11/2024 12:01:41,Started,1080,06/14/2023 12:36:09,11/03/2022 18:30:39
1,05/01/2023 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Poojitha,08/16/2000,Female,India,SAINT LOUIS,Information Systems,03/11/2024 12:01:41,Started,1080,05/01/2023 06:08:21,11/03/2022 18:30:39
2,04/09/2023 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Emmanuel,01/27/2002,Male,United States,Illinois Institute of Technology,Computer Science,03/11/2024 12:01:41,Started,1080,05/11/2023 1085640:21:29,11/03/2022 18:30:39
3,08/29/2023 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Amrutha Varshini,11/01/1999,Female,United States,Saint Louis University,Information Systems,03/11/2024 12:01:41,Team Allocated,1070,10/09/2023 22:02:42,11/03/2022 18:30:39
4,01/06/2023 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Vinay Varshith,04/19/2000,Male,United States,Saint Louis University,Computer Science,03/11/2024 12:01:41,Started,1080,01/06/2023 15:40:10,11/03/2022 18:30:39

In [ ]:
#Column type, non-null, memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8558 entries, 0 to 8557
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Learner SignUp DateTime  8558 non-null   object
 1   Opportunity Id           8558 non-null   object
 2   Opportunity Name         8558 non-null   object
 3   Opportunity Category     8558 non-null   object
 4   Opportunity End Date     8558 non-null   object
 5   First Name               8558 non-null   object
 6   Date of Birth            8558 non-null   object
 7   Gender                   8558 non-null   object
 8   Country                  8558 non-null   object
 9   Institution Name         8553 non-null   object
 10  Current/Intended Major   8553 non-null   object
 11  Entry created at         8558 non-null   object
 12  Status Description       8558 non-null   object
 13  Status Code              8558 non-null   int64
 14  Apply Date               8558 non-null   object
 15  Opportunity Start Date   4764 non-null   object
dtypes: int64(1), object(15)
memory usage: 1.0+ MB

In [ ]:
#Data type of each column
df.dtypes

Learner SignUp DateTime    object
Opportunity Id             object
Opportunity Name           object
Opportunity Category       object
Opportunity End Date       object
First Name                 object
Date of Birth              object
Gender                     object
Country                    object
Institution Name           object
Current/Intended Major     object
Entry created at           object
Status Description         object
Status Code                 int64
Apply Date                 object
Opportunity Start Date     object
dtype: object

In [ ]:
#Count value Contries
df['Country'].value_counts()

Country
United States             3976
India                     2836
Nigeria                    760
Ghana                      275
Pakistan                   219
                          ...
Ireland                      1
Libyan Arab Jamahiriya       1
Afghanistan                  1
Bhutan                       1
Spain                        1
Name: count, Length: 71, dtype: int64

In [ ]:
df['Institution Name'].value_counts()

Institution Name
Saint Louis University                 2631
saint louis university                  818
Saint Louis university                  246
Saint louis university                  214
SAINT LOUIS UNIVERSITY                  106
                                       ...
Ram Lalit Singh Mahavidya                 1
federal university  Lokoja                1
Ashoka Academy                            1
GEMS New Millennium School Al Khail       1
Nwihs                                     1
Name: count, Length: 2089, dtype: int64

HANDLING MISSING VALUES

In [ ]:
print("total_count of Missing Values :-",df.isna().sum().sum())

# Missing percentages
print((df.isnull().sum() / len(df)) * 100)

total_count of Missing Values :- 3804
Learner SignUp DateTime     0.000000
Opportunity Id              0.000000
Opportunity Name            0.000000
Opportunity Category        0.000000
Opportunity End Date        0.000000
First Name                  0.000000
Date of Birth               0.000000
Gender                      0.000000
Country                     0.000000
Institution Name            0.058425
Current/Intended Major      0.058425
Entry created at            0.000000
Status Description          0.000000
Status Code                 0.000000
Apply Date                  0.000000
Opportunity Start Date     44.332788
dtype: float64

In [ ]:
#number of missing columns
df.isnull().sum()

Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date          0
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              5
Current/Intended Major        5
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     3794
dtype: int64

In [ ]:
#Drop missing values
df.dropna()

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date
0,06/14/2023 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Faria,01/12/2001,Female,Pakistan,Nwihs,Radiology,03/11/2024 12:01:41,Started,1080,06/14/2023 12:36:09,11/03/2022 18:30:39
1,05/01/2023 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Poojitha,08/16/2000,Female,India,SAINT LOUIS,Information Systems,03/11/2024 12:01:41,Started,1080,05/01/2023 06:08:21,11/03/2022 18:30:39
2,04/09/2023 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Emmanuel,01/27/2002,Male,United States,Illinois Institute of Technology,Computer Science,03/11/2024 12:01:41,Started,1080,05/11/2023 1085640:21:29,11/03/2022 18:30:39
3,08/29/2023 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Amrutha Varshini,11/01/1999,Female,United States,Saint Louis University,Information Systems,03/11/2024 12:01:41,Team Allocated,1070,10/09/2023 22:02:42,11/03/2022 18:30:39
4,01/06/2023 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Vinay Varshith,04/19/2000,Male,United States,Saint Louis University,Computer Science,03/11/2024 12:01:41,Started,1080,01/06/2023 15:40:10,11/03/2022 18:30:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8553,03/05/2024 16:39:21,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,03/08/2024 11:30:00,Selam,10/14/2006,Female,Ethiopia,Lideta Catholic Cathedral School,Computer Science,03/11/2024 12:03:14,Team Allocated,1070,03/05/2024 17:10:41,03/08/2024 14:00:00
8554,03/06/2024 15:58:47,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,03/08/2024 11:30:00,Gowri Sailesh,05/18/1999,Male,United States,SAINT LOUIS UNIVERSITY,Information Systems,03/11/2024 12:03:14,Team Allocated,1070,03/06/2024 18:22:11,03/08/2024 14:00:00
8555,02/29/2024 15:02:31,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,03/08/2024 11:30:00,Abiola,03/16/1999,Male,Nigeria,Tai Solarin university of Education,Political Science,03/11/2024 12:03:14,Team Allocated,1070,02/29/2024 15:10:06,03/08/2024 14:00:00
8556,12/23/2023 03:53:12,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,03/08/2024 11:30:00,venumadhavi,06/05/1997,Female,United States,Saint Louis University,Information Systems,03/11/2024 12:03:14,Team Allocated,1070,02/27/2024 06:48:47,03/08/2024 14:00:00
8557,06/01/2023 13:22:01,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,03/08/2024 11:30:00,Prashanth Reddy,11/30/2000,Male,India,Saint Louis University,Artificial Intelligence,03/11/2024 12:03:14,Team Allocated,1070,02/16/2024 16:33:00,03/08/2024 14:00:00

HANDLING DUPLICATE

In [ ]:
#number of Duplicate
df.duplicated().sum()

np.int64(0)

In [ ]:
#Student applied for same opportunity
df.duplicated(subset=['First Name', 'Date of Birth', 'Opportunity Id']).sum()

np.int64(122)

In [ ]:
#Names of Students who applied for same opportunity
student = df.duplicated(subset=['First Name', 'Date of Birth', 'Opportunity Id'])
df[student] ['First Name']

184            Abdu
212       Manikanta
386        Muhammad
551        Sindhura
874          Shreya
           ...
7737    Sai Kowshik
7749        Saiteja
7756      Oyebusola
7758          Vinay
7772           Abdu
Name: First Name, Length: 122, dtype: object

In [ ]:
# Remove duplicate student
df_clean = df.drop_duplicates(subset=['First Name', 'Date of Birth'])

#count unique students
unique_students = df_clean[['First Name', 'Date of Birth']].drop_duplicates()
print(f"Unique students: {unique_students}")

Unique students:             First Name Date of Birth
0                Faria    01/12/2001
1             Poojitha    08/16/2000
2             Emmanuel    01/27/2002
3     Amrutha Varshini    11/01/1999
4       Vinay Varshith    04/19/2000
...                ...           ...
8525           Gobburi    05/15/2001
8526         Saathwika    05/02/2002
8535            Fabian    02/22/2000
8545            Victor    04/02/1999
8555            Abiola    03/16/1999

[3850 rows x 2 columns]

In [ ]:
# Show gender counts after remove duplicates
df_clean['Gender'].value_counts()

Gender
Male                     2264
Female                   1576
Don't want to specify       8
Other                       2
Name: count, dtype: int64

In [ ]:
df.drop_duplicates(subset=['First Name', 'Date of Birth'])['Gender'].value_counts(normalize=True) * 100

Gender
Male                     58.805195
Female                   40.935065
Don't want to specify     0.207792
Other                     0.051948
Name: proportion, dtype: float64

In [ ]:
#Remove Duplicate
df = df.drop_duplicates()

FORMATTING INCONSISTENTS

In [ ]:
text_columns = ['Gender', 'Country', 'Opportunity Category', 'Status Description', 'Institution Name']
for col in text_columns:
  print(f"\n Unique values check for: {col}")
  print(df[col].value_counts(dropna=False).head(10))

 Unique values check for: Gender
Gender
Male                     5018
Female                   3522
Don't want to specify      15
Other                       3
Name: count, dtype: int64

 Unique values check for: Country
Country
United States    3976
India            2836
Nigeria           760
Ghana             275
Pakistan          219
Bangladesh         65
Egypt              50
Ethiopia           38
Kenya              38
Rwanda             28
Name: count, dtype: int64

 Unique values check for: Opportunity Category
Opportunity Category
Internship     5421
Course         2037
Event           545
Competition     425
Engagement      130
Name: count, dtype: int64

 Unique values check for: Status Description
Status Description
Rejected          3569
Team Allocated    3276
Started            767
Dropped Out        617
Waitlisted         109
Applied            105
Withdraw            86
Rewards Award       29
Name: count, dtype: int64

 Unique values check for: Institution Name
Institution Name
Saint Louis University              2631
saint louis university               818
Saint Louis university               246
Saint louis university               214
SAINT LOUIS UNIVERSITY               106
Illinois Institute of Technology     103
Saint louis University               102
Webster University                    46
St Louis University                   43
Saint Louis                           37
Name: count, dtype: int64

In [ ]:
# Convert date columns
date_columns = [
    'Learner SignUp DateTime', 'Date of Birth', 'Entry created at',
    'Apply Date', 'Opportunity Start Date', 'Opportunity End Date'
]
for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

#  Log timestamp
log_time = pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')

#  Identify logic errors
error_end_before_start = df['Opportunity End Date'] < df['Opportunity Start Date']
error_apply_after_end = df['Apply Date'] > df['Opportunity End Date']

print(f"[{log_time}] End Date < Start Date: {error_end_before_start.sum()} rows")
print(f"[{log_time}] Apply Date > End Date: {error_apply_after_end.sum()} rows")

# Fix swapped Start/End dates instead of deleting the rows
swap_mask = error_end_before_start
old_start = df.loc[swap_mask, 'Opportunity Start Date'].copy()
df.loc[swap_mask, 'Opportunity Start Date'] = df.loc[swap_mask, 'Opportunity End Date']
df.loc[swap_mask, 'Opportunity End Date'] = old_start
print(f"[{log_time}] Swapped Start/End dates for: {swap_mask.sum()} rows")

# Re-check for any remaining logic errors after the swap
still_bad = (df['Opportunity End Date'] < df['Opportunity Start Date']) | (df['Apply Date'] > df['Opportunity End Date'])
print(f"[{log_time}] Remaining logic errors after swap: {still_bad.sum()} rows")

# Only drop rows if still invalid after the swap attempt
df = df[~still_bad].copy()

print(f"[{log_time}] Final dataset size: {len(df)} rows")

[2026-07-18 17:23:52] End Date < Start Date: 527 rows
[2026-07-18 17:23:52] Apply Date > End Date: 0 rows
[2026-07-18 17:23:52] Swapped Start/End dates for: 527 rows
[2026-07-18 17:23:52] Remaining logic errors after swap: 0 rows
[2026-07-18 17:23:52] Final dataset size: 8558 rows

In [ ]:

# Force text type, remove spaces, standardize capitalization
df['First Name'] = df['First Name'].astype(str).str.strip().str.lower().str.title()

#  Replace names with numbers or symbols as 'Unknown'
df['First Name'] = df['First Name'].replace(r'.*[\d@?#!$%^&*()].*', 'Unknown', regex=True)

#Handle missing text variations
df['First Name'] = df['First Name'].replace(['Nan', 'None', ''], np.nan)

# Quick check: how many were converted to Unknown?
unknown_count = (df['First Name'] == 'Unknown').sum()
print(f"Rows converted to 'Unknown': {unknown_count}")

# Quick check: sample of cleaned names
print("\n of clean first names:")
print(df['First Name'].dropna().head(10))

Rows converted to 'Unknown': 22

 of clean first names:
0               Faria
1            Poojitha
2            Emmanuel
3    Amrutha Varshini
4      Vinay Varshith
5                 Mor
6             Fardeen
7               Gauri
8           Siddharth
9            Vanshika
Name: First Name, dtype: object

In [ ]:
#Clean: remove extra spaces and standardize capitalization for ALL institutions
df['Institution Name'] = df['Institution Name'].str.strip().str.title()

#Define the cleaning for Saint Louis University variations
standard_name_cleaning = {
    'Saint Louis University': 'Saint Louis University',
    'Saint Louis Univeristy': 'Saint Louis University',
    'St Louis University': 'Saint Louis University',
    'St. Louis University': 'Saint Louis University',
    'Slu': 'Saint Louis University',
    'Sl U': 'Saint Louis University',
    'Saint Louis Univ': 'Saint Louis University',
    'Saint Louis': 'Saint Louis University',
    'Saint Louis University ': 'Saint Louis University',
    'Saint Louise University': 'Saint Louis University',
    'Saint Louis Univerisity': 'Saint Louis University',
    'Saint Louis Univesity': 'Saint Louis University',
    'Saint Louis Universy': 'Saint Louis University',
    'Saint Louis University-Main Campus': 'Saint Louis University',
    'Saint Louis University I': 'Saint Louis University',
    'Saint Louis University  Saint Louis Missouri': 'Saint Louis University',
    'Saint Louis Unveracity': 'Saint Louis University',
    'Saint Louis Universty': 'Saint Louis University',
    'Saint Louis Univercity': 'Saint Louis University',
    'Saint Louis University  Mo': 'Saint Louis University',
    'Saint Louis  University': 'Saint Louis University',
    'Saint Louis Unniversity': 'Saint Louis University',
    'Saint Louis University- Madrid': 'Saint Louis University',
    'Saint Louisuniversity': 'Saint Louis University',
    'University Of Missouri Saint Louis': 'Saint Louis University',
    'Saint Louis University Madrid': 'Saint Louis University',
    'Saint Louis University-Madrid': 'Saint Louis University',
}

#Apply the cleaning
df['Institution Name'] = df['Institution Name'].replace(standard_name_cleaning)

#Fill missing values
df['Institution Name'] = df['Institution Name'].fillna('Unknown')

# Verify the cleaning
print(df['Institution Name'].value_counts().head(10))

Institution Name
Saint Louis University                                4487
Illinois Institute Of Technology                       152
Webster University                                      72
Kwame Nkrumah University Of Science And Technology      35
Srm University                                          32
University Of Ibadan                                    27
Vishnu Institute Of Technology                          25
Chandigarh University                                   24
Vellore Institute Of Technology                         23
Cmr Engineering College                                 21
Name: count, dtype: int64

In [ ]:
print(f"Unique Countries: {df['Country'].nunique()}")
print(f"Unique Institutions: {df['Institution Name'].nunique()}")

Unique Countries: 71
Unique Institutions: 1796

COLUMN ORDER

In [ ]:
column_order = [
    # Student information
    'First Name',
    'Date of Birth',
    'Gender',
    'Country',
    'Institution Name',
    'Current/Intended Major',

    # Opportunity information
    'Opportunity Id',
    'Opportunity Name',
    'Opportunity Category',
    'Opportunity Start Date',
    'Opportunity End Date',

    # Engagement timeline
    'Learner SignUp DateTime',
    'Apply Date',
    'Entry created at',

    # Application outcomes
    'Status Description',
    'Status Code'
]

df = df[column_order]

In [ ]:
print(df.columns.tolist())

['First Name', 'Date of Birth', 'Gender', 'Country', 'Institution Name', 'Current/Intended Major', 'Opportunity Id', 'Opportunity Name', 'Opportunity Category', 'Opportunity Start Date', 'Opportunity End Date', 'Learner SignUp DateTime', 'Apply Date', 'Entry created at', 'Status Description', 'Status Code']

Save clean_dataset_scv

In [ ]:
# Save and trigger a download
from google.colab import files

df.to_csv('cleaned_data.csv', index=False)
files.download('cleaned_data.csv')